### ISSUE TITLE
expo link doesnt work? (403)

### ISSUE THREAD

**Issue by nicholasareed** [engineerStuardo/reactNativeMyMoviesAppTest#1]
May I get an invite to @nicholasareed please?

**Comment by engineerStuardo** [comment]
can you please show me the error?

**Comment by nicholasareed** [comment]
<img width="1147" alt="Screen Shot 2021-07-06 at 11 58 33 AM" src="https://user-images.githubusercontent.com/801236/124652922-8cbf5a00-de51-11eb-8116-29671e8a79ff.png">
